-- Prisma schema translated to plain PostgreSQL DDL.
-- Drops existing objects first so the script can be rerun cleanly.

DROP TABLE IF EXISTS "ReminderLog" CASCADE;
DROP TABLE IF EXISTS "GroomingRecord" CASCADE;
DROP TABLE IF EXISTS "AppointmentService" CASCADE;
DROP TABLE IF EXISTS "Appointment" CASCADE;
DROP TABLE IF EXISTS "Service" CASCADE;
DROP TABLE IF EXISTS "Pet" CASCADE;
DROP TABLE IF EXISTS "Customer" CASCADE;
DROP TABLE IF EXISTS "UserBranch" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS "Branch" CASCADE;

DROP TYPE IF EXISTS "ReminderStatus" CASCADE;
DROP TYPE IF EXISTS "AppointmentSource" CASCADE;
DROP TYPE IF EXISTS "AppointmentStatus" CASCADE;
DROP TYPE IF EXISTS "PetSize" CASCADE;
DROP TYPE IF EXISTS "Species" CASCADE;
DROP TYPE IF EXISTS "Role" CASCADE;

CREATE TYPE "Role" AS ENUM ('manager', 'staff', 'groomer');
CREATE TYPE "AppointmentStatus" AS ENUM (
  'scheduled',
  'confirmed',
  'checked_in',
  'in_progress',
  'completed',
  'cancelled',
  'no_show'
);
CREATE TYPE "AppointmentSource" AS ENUM ('whatsapp', 'phone', 'walk_in', 'online');
CREATE TYPE "Species" AS ENUM ('perro', 'gato', 'otro');
CREATE TYPE "PetSize" AS ENUM ('pequeno', 'mediano', 'grande', 'gigante');
CREATE TYPE "ReminderStatus" AS ENUM ('drafted', 'sent', 'skipped');

CREATE TABLE "Branch" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "address" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL UNIQUE,
  "phone" TEXT NOT NULL,
  "role" "Role" NOT NULL,
  "calendarColor" TEXT,
  "active" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "UserBranch" (
  "userId" INT NOT NULL,
  "branchId" INT NOT NULL,
  PRIMARY KEY ("userId", "branchId"),
  CONSTRAINT "UserBranch_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE,
  CONSTRAINT "UserBranch_branchId_fkey"
    FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE CASCADE
);

CREATE TABLE "Customer" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "whatsappOptIn" BOOLEAN NOT NULL DEFAULT FALSE,
  "notes" TEXT NOT NULL DEFAULT '',
  "createdAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Pet" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customerId" INT NOT NULL,
  "name" TEXT NOT NULL,
  "species" "Species" NOT NULL,
  "breed" TEXT NOT NULL,
  "size" "PetSize" NOT NULL,
  "profilePhotoUrl" TEXT,
  "birthdate" TIMESTAMP(3) WITH TIME ZONE,
  "ageEstimate" TEXT,
  "healthNotes" TEXT NOT NULL DEFAULT '',
  "behaviorNotes" TEXT NOT NULL DEFAULT '',
  "createdAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Pet_customerId_fkey"
    FOREIGN KEY ("customerId") REFERENCES "Customer" ("id") ON DELETE CASCADE
);

CREATE TABLE "Service" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "estimatedDurationMinutes" INT NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Appointment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "branchId" INT NOT NULL,
  "petId" INT NOT NULL,
  "groomerId" INT NOT NULL,
  "createdById" INT NOT NULL,
  "scheduledStart" TIMESTAMP(3) WITH TIME ZONE NOT NULL,
  "scheduledEnd" TIMESTAMP(3) WITH TIME ZONE NOT NULL,
  "status" "AppointmentStatus" NOT NULL DEFAULT 'scheduled',
  "source" "AppointmentSource" NOT NULL,
  "notes" TEXT NOT NULL DEFAULT '',
  "createdAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Appointment_branchId_fkey"
    FOREIGN KEY ("branchId") REFERENCES "Branch" ("id"),
  CONSTRAINT "Appointment_petId_fkey"
    FOREIGN KEY ("petId") REFERENCES "Pet" ("id"),
  CONSTRAINT "Appointment_groomerId_fkey"
    FOREIGN KEY ("groomerId") REFERENCES "User" ("id"),
  CONSTRAINT "Appointment_createdById_fkey"
    FOREIGN KEY ("createdById") REFERENCES "User" ("id")
);

CREATE TABLE "AppointmentService" (
  "appointmentId" INT NOT NULL,
  "serviceId" INT NOT NULL,
  PRIMARY KEY ("appointmentId", "serviceId"),
  CONSTRAINT "AppointmentService_appointmentId_fkey"
    FOREIGN KEY ("appointmentId") REFERENCES "Appointment" ("id") ON DELETE CASCADE,
  CONSTRAINT "AppointmentService_serviceId_fkey"
    FOREIGN KEY ("serviceId") REFERENCES "Service" ("id")
);

CREATE TABLE "GroomingRecord" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appointmentId" INT NOT NULL UNIQUE,
  "actualStart" TIMESTAMP(3) WITH TIME ZONE,
  "actualEnd" TIMESTAMP(3) WITH TIME ZONE,
  "groomerNotes" TEXT NOT NULL DEFAULT '',
  "outcome" TEXT NOT NULL DEFAULT '',
  "intakeSignatureName" TEXT,
  "intakeSignatureImageUrl" TEXT,
  "intakeSignedAt" TIMESTAMP(3) WITH TIME ZONE,
  "completionSignatureName" TEXT,
  "completionSignatureImageUrl" TEXT,
  "completionSignedAt" TIMESTAMP(3) WITH TIME ZONE,
  "satisfactionNotes" TEXT NOT NULL DEFAULT '',
  "beforePhotoUrl" TEXT,
  "afterPhotoUrl" TEXT,
  "createdAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "GroomingRecord_appointmentId_fkey"
    FOREIGN KEY ("appointmentId") REFERENCES "Appointment" ("id") ON DELETE CASCADE
);

CREATE TABLE "ReminderLog" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appointmentId" INT NOT NULL,
  "channel" TEXT NOT NULL DEFAULT 'whatsapp',
  "messageTemplate" TEXT NOT NULL,
  "manualStatus" "ReminderStatus" NOT NULL DEFAULT 'drafted',
  "timestamp" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ReminderLog_appointmentId_fkey"
    FOREIGN KEY ("appointmentId") REFERENCES "Appointment" ("id") ON DELETE CASCADE
);

CREATE INDEX "Appointment_branchId_scheduledStart_idx"
  ON "Appointment" ("branchId", "scheduledStart");
CREATE INDEX "Appointment_groomerId_scheduledStart_scheduledEnd_idx"
  ON "Appointment" ("groomerId", "scheduledStart", "scheduledEnd");
CREATE INDEX "Appointment_petId_scheduledStart_idx"
  ON "Appointment" ("petId", "scheduledStart");

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "Branch_set_updated_at"
  BEFORE UPDATE ON "Branch"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER "User_set_updated_at"
  BEFORE UPDATE ON "User"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER "Customer_set_updated_at"
  BEFORE UPDATE ON "Customer"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER "Pet_set_updated_at"
  BEFORE UPDATE ON "Pet"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER "Service_set_updated_at"
  BEFORE UPDATE ON "Service"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER "Appointment_set_updated_at"
  BEFORE UPDATE ON "Appointment"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER "GroomingRecord_set_updated_at"
  BEFORE UPDATE ON "GroomingRecord"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
