ALTER TABLE public.configuracion_sistema
    ADD COLUMN IF NOT EXISTS habilitar_calificaciones BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS public.calificaciones_groomer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    peluquero_id BIGINT NOT NULL REFERENCES public.peluqueros(id) ON DELETE RESTRICT,
    mascota_id BIGINT NOT NULL REFERENCES public.mascotas(id) ON DELETE RESTRICT,
    registro_servicio_id BIGINT NOT NULL UNIQUE REFERENCES public.registros_servicio(id) ON DELETE RESTRICT,
    calificacion SMALLINT NOT NULL CHECK (calificacion BETWEEN 0 AND 5),
    calificacion_notas TEXT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_calificaciones_groomer_peluquero ON public.calificaciones_groomer (peluquero_id);
CREATE INDEX IF NOT EXISTS ix_calificaciones_groomer_mascota ON public.calificaciones_groomer (mascota_id);

ALTER TABLE public.calificaciones_groomer ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.calificaciones_groomer FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.configuracion_sistema_actualizar(
    p_foto_antes_requerida BOOLEAN,
    p_foto_despues_requerida BOOLEAN,
    p_dias_anticipacion_recordatorio INTEGER,
    p_metodo_pago_cupon_id BIGINT,
    p_habilitar_calificaciones BOOLEAN
)
RETURNS public.configuracion_sistema
LANGUAGE plpgsql SECURITY INVOKER SET search_path = ''
AS $$
DECLARE
    v_anterior public.configuracion_sistema;
    v_fila public.configuracion_sistema;
BEGIN
    PERFORM petstore_private.requerir_admin_propietario();
    PERFORM petstore_private.establecer_actor();

    IF NOT EXISTS (
        SELECT 1 FROM public.metodos_pago mp
        WHERE mp.id = p_metodo_pago_cupon_id AND mp.activo = TRUE
    ) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'METODO_PAGO_CUPON_INVALIDO';
    END IF;

    SELECT * INTO v_anterior FROM public.configuracion_sistema WHERE id = 1 FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'CONFIGURACION_SISTEMA_NO_ENCONTRADA';
    END IF;

    UPDATE public.configuracion_sistema
    SET foto_antes_requerida = p_foto_antes_requerida,
        foto_despues_requerida = p_foto_despues_requerida,
        dias_anticipacion_recordatorio = p_dias_anticipacion_recordatorio,
        metodo_pago_cupon_id = p_metodo_pago_cupon_id,
        habilitar_calificaciones = p_habilitar_calificaciones
    WHERE id = 1
    RETURNING * INTO v_fila;

    PERFORM petstore_private.auditar_cambio('configuracion_sistema', '1', 'actualizar', TO_JSONB(v_anterior), TO_JSONB(v_fila), NULL, NULL);
    RETURN v_fila;
EXCEPTION
    WHEN check_violation OR not_null_violation OR foreign_key_violation THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'DATOS_INVALIDOS';
END;
$$;

REVOKE ALL ON FUNCTION public.configuracion_sistema_actualizar(BOOLEAN, BOOLEAN, INTEGER, BIGINT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.configuracion_sistema_actualizar(BOOLEAN, BOOLEAN, INTEGER, BIGINT, BOOLEAN) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.configuracion_sistema_actualizar(BOOLEAN, BOOLEAN, INTEGER, BIGINT, BOOLEAN) TO authenticated, service_role;
