BEGIN;

CREATE TABLE public.registros_servicio_fotos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_servicio_id BIGINT NOT NULL
        REFERENCES public.registros_servicio(id) ON DELETE RESTRICT,
    momento TEXT NOT NULL CHECK (momento IN ('ingreso', 'egreso')),
    ruta_storage TEXT NOT NULL
        CHECK (BTRIM(ruta_storage) LIKE 'services/%'),
    subida_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (registro_servicio_id, ruta_storage)
);

CREATE INDEX ix_registros_servicio_fotos_registro_momento
    ON public.registros_servicio_fotos (registro_servicio_id, momento, id);

INSERT INTO public.registros_servicio_fotos (
    registro_servicio_id,
    momento,
    ruta_storage,
    subida_en
)
SELECT id, 'ingreso', foto_antes_url, COALESCE(foto_antes_subida_en, creado_en)
FROM public.registros_servicio
WHERE foto_antes_url IS NOT NULL
UNION ALL
SELECT id, 'egreso', foto_despues_url, COALESCE(foto_despues_subida_en, creado_en)
FROM public.registros_servicio
WHERE foto_despues_url IS NOT NULL
ON CONFLICT (registro_servicio_id, ruta_storage) DO NOTHING;

ALTER TABLE public.registros_servicio_fotos ENABLE ROW LEVEL SECURITY;

CREATE POLICY registros_servicio_fotos_select
ON public.registros_servicio_fotos FOR SELECT TO authenticated
USING (
    (SELECT petstore_private.usuario_activo())
    AND (SELECT petstore_private.puede_acceder_registro(registro_servicio_id))
);

REVOKE ALL PRIVILEGES ON TABLE public.registros_servicio_fotos FROM anon, authenticated;
GRANT SELECT ON TABLE public.registros_servicio_fotos TO authenticated;
GRANT ALL PRIVILEGES ON TABLE public.registros_servicio_fotos TO service_role;
REVOKE ALL PRIVILEGES ON SEQUENCE public.registros_servicio_fotos_id_seq FROM anon, authenticated;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.registros_servicio_fotos_id_seq TO service_role;

CREATE FUNCTION public.registros_servicio_fotos_agregar(
    p_registro_servicio_id BIGINT,
    p_fotos_ingreso TEXT[] DEFAULT ARRAY[]::TEXT[],
    p_fotos_egreso TEXT[] DEFAULT ARRAY[]::TEXT[]
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_registro public.registros_servicio;
    v_cita public.citas;
    v_resultado JSONB;
BEGIN
    PERFORM petstore_private.requerir_usuario_activo();
    PERFORM petstore_private.establecer_actor();

    SELECT * INTO v_registro
    FROM public.registros_servicio
    WHERE id = p_registro_servicio_id
    FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'REGISTRO_NO_ENCONTRADO';
    END IF;

    SELECT * INTO v_cita FROM public.citas WHERE id = v_registro.cita_id;
    PERFORM petstore_private.requerir_acceso_sucursal(v_cita.sucursal_id);

    IF v_registro.estado = 'completado' AND NOT petstore_private.es_admin_propietario() THEN
        RAISE EXCEPTION USING ERRCODE = 'PA001', MESSAGE = 'SOLO_ADMIN_PUEDE_EDITAR_COMPLETADO';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM UNNEST(COALESCE(p_fotos_ingreso, ARRAY[]::TEXT[]) || COALESCE(p_fotos_egreso, ARRAY[]::TEXT[])) ruta
        WHERE ruta IS NULL OR BTRIM(ruta) = '' OR ruta NOT LIKE 'services/%'
    ) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'RUTA_FOTO_INVALIDA';
    END IF;

    INSERT INTO public.registros_servicio_fotos (registro_servicio_id, momento, ruta_storage)
    SELECT p_registro_servicio_id, foto.momento, BTRIM(foto.ruta)
    FROM (
        SELECT 'ingreso'::TEXT AS momento, UNNEST(COALESCE(p_fotos_ingreso, ARRAY[]::TEXT[])) AS ruta
        UNION ALL
        SELECT 'egreso'::TEXT, UNNEST(COALESCE(p_fotos_egreso, ARRAY[]::TEXT[]))
    ) foto
    ON CONFLICT (registro_servicio_id, ruta_storage) DO NOTHING;

    SELECT COALESCE(JSONB_AGG(TO_JSONB(f) ORDER BY f.momento, f.id), '[]'::JSONB)
    INTO v_resultado
    FROM public.registros_servicio_fotos f
    WHERE f.registro_servicio_id = p_registro_servicio_id;

    RETURN v_resultado;
END;
$$;

CREATE FUNCTION public.registros_servicio_fotos_listar(
    p_registro_servicio_id BIGINT,
    p_momento TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_sucursal_id BIGINT;
    v_resultado JSONB;
BEGIN
    PERFORM petstore_private.requerir_usuario_activo();
    SELECT c.sucursal_id INTO v_sucursal_id
    FROM public.registros_servicio rs
    INNER JOIN public.citas c ON c.id = rs.cita_id
    WHERE rs.id = p_registro_servicio_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'REGISTRO_NO_ENCONTRADO';
    END IF;
    PERFORM petstore_private.requerir_acceso_sucursal(v_sucursal_id);

    IF p_momento IS NOT NULL AND p_momento NOT IN ('ingreso', 'egreso') THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'MOMENTO_FOTO_INVALIDO';
    END IF;

    SELECT COALESCE(JSONB_AGG(TO_JSONB(f) ORDER BY f.id), '[]'::JSONB)
    INTO v_resultado
    FROM public.registros_servicio_fotos f
    WHERE f.registro_servicio_id = p_registro_servicio_id
      AND (p_momento IS NULL OR f.momento = p_momento);

    RETURN v_resultado;
END;
$$;

CREATE OR REPLACE FUNCTION public.registros_servicio_listar(
    p_limite BIGINT DEFAULT NULL,
    p_offset BIGINT DEFAULT 0,
    p_sucursal_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE v_resultado JSONB;
BEGIN
    PERFORM petstore_private.requerir_usuario_activo();
    PERFORM petstore_private.validar_paginacion(p_limite, p_offset);
    WITH base AS (
        SELECT rs.*
        FROM public.registros_servicio rs
        INNER JOIN public.citas c ON c.id = rs.cita_id
        WHERE rs.activo = TRUE
          AND (p_sucursal_id IS NULL OR c.sucursal_id = p_sucursal_id)
          AND petstore_private.tiene_acceso_sucursal(c.sucursal_id)
    ),
    pagina AS (SELECT * FROM base ORDER BY id ASC LIMIT p_limite OFFSET p_offset)
    SELECT JSONB_BUILD_OBJECT(
        'datos', COALESCE((
            SELECT JSONB_AGG(
                TO_JSONB(p) || JSONB_BUILD_OBJECT(
                    'adicionales', COALESCE((
                        SELECT JSONB_AGG(TO_JSONB(a) ORDER BY a.servicio_id)
                        FROM public.registros_servicio_adicionales a
                        WHERE a.registro_servicio_id = p.id AND a.activo = TRUE
                    ), '[]'::JSONB),
                    'fotos', COALESCE((
                        SELECT JSONB_AGG(TO_JSONB(f) ORDER BY f.momento, f.id)
                        FROM public.registros_servicio_fotos f
                        WHERE f.registro_servicio_id = p.id
                    ), '[]'::JSONB)
                )
                ORDER BY p.id
            )
            FROM pagina p
        ), '[]'::JSONB),
        'total', (SELECT COUNT(*) FROM base), 'limite', p_limite, 'offset', p_offset
    ) INTO v_resultado;
    RETURN v_resultado;
END;
$$;

CREATE OR REPLACE FUNCTION public.registros_servicio_listar_todos(
    p_limite BIGINT DEFAULT NULL,
    p_offset BIGINT DEFAULT 0
)
RETURNS JSONB
LANGUAGE plpgsql SECURITY INVOKER SET search_path = ''
AS $$
DECLARE v_resultado JSONB;
BEGIN
    PERFORM petstore_private.requerir_admin_propietario();
    PERFORM petstore_private.validar_paginacion(p_limite, p_offset);
    WITH base AS (SELECT * FROM public.registros_servicio),
    pagina AS (SELECT * FROM base ORDER BY id ASC LIMIT p_limite OFFSET p_offset)
    SELECT JSONB_BUILD_OBJECT(
        'datos', COALESCE((
            SELECT JSONB_AGG(
                TO_JSONB(p) || JSONB_BUILD_OBJECT(
                    'fotos', COALESCE((
                        SELECT JSONB_AGG(TO_JSONB(f) ORDER BY f.momento, f.id)
                        FROM public.registros_servicio_fotos f
                        WHERE f.registro_servicio_id = p.id
                    ), '[]'::JSONB)
                )
                ORDER BY p.id
            )
            FROM pagina p
        ), '[]'::JSONB),
        'total', (SELECT COUNT(*) FROM base), 'limite', p_limite, 'offset', p_offset
    ) INTO v_resultado;
    RETURN v_resultado;
END;
$$;

REVOKE ALL ON FUNCTION public.registros_servicio_fotos_agregar(BIGINT, TEXT[], TEXT[]) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.registros_servicio_fotos_listar(BIGINT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.registros_servicio_fotos_agregar(BIGINT, TEXT[], TEXT[]) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.registros_servicio_fotos_listar(BIGINT, TEXT) TO authenticated, service_role;

DO $$
DECLARE v_funcion RECORD;
BEGIN
    FOR v_funcion IN
        SELECT n.nspname AS esquema, p.proname AS nombre,
               PG_GET_FUNCTION_IDENTITY_ARGUMENTS(p.oid) AS argumentos
        FROM pg_proc p
        INNER JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = 'public'
          AND p.proname IN (
              'registros_servicio_insertar',
              'registros_servicio_iniciar',
              'registros_servicio_actualizar',
              'registros_servicio_completar'
          )
    LOOP
        EXECUTE FORMAT('DROP FUNCTION %I.%I(%s)', v_funcion.esquema, v_funcion.nombre, v_funcion.argumentos);
    END LOOP;
END;
$$;

CREATE FUNCTION public.registros_servicio_insertar(
    p_cita_id BIGINT,
    p_servicio_id BIGINT,
    p_peluquero_id BIGINT,
    p_tamano_id BIGINT,
    p_heridas_visibles BOOLEAN,
    p_raspones BOOLEAN,
    p_piel_irritada BOOLEAN,
    p_costras BOOLEAN,
    p_inflamacion BOOLEAN,
    p_cojera BOOLEAN,
    p_dolor_al_tocar BOOLEAN,
    p_pulgas BOOLEAN,
    p_garrapatas BOOLEAN,
    p_piojos BOOLEAN,
    p_observaciones_ingreso TEXT,
    p_firma_ingreso_url TEXT,
    p_notas_servicio TEXT
)
RETURNS public.registros_servicio
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
    v_cita_anterior public.citas;
    v_cita_nueva public.citas;
    v_mascota_anterior public.mascotas;
    v_mascota_nueva public.mascotas;
    v_registro public.registros_servicio;
    v_duracion INTEGER;
BEGIN
    PERFORM petstore_private.requerir_usuario_activo();
    PERFORM petstore_private.establecer_actor();

    SELECT * INTO v_cita_anterior
    FROM public.citas
    WHERE id = p_cita_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'CITA_NO_ENCONTRADA';
    END IF;

    PERFORM petstore_private.requerir_acceso_sucursal(v_cita_anterior.sucursal_id);

    IF NOT EXISTS (
        SELECT 1 FROM public.sucursales s
        WHERE s.id = v_cita_anterior.sucursal_id AND s.activo = TRUE
    ) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'SUCURSAL_INACTIVA_O_INVALIDA';
    END IF;

    SELECT * INTO v_mascota_anterior
    FROM public.mascotas m
    WHERE m.id = v_cita_anterior.mascota_id
      AND m.activo = TRUE
      AND EXISTS (
          SELECT 1 FROM public.clientes c
          WHERE c.id = m.cliente_id AND c.activo = TRUE
      )
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'MASCOTA_INACTIVA_O_INVALIDA';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.servicios s WHERE s.id = p_servicio_id AND s.activo = TRUE) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'SERVICIO_INACTIVO_O_INVALIDO';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.peluqueros p WHERE p.id = p_peluquero_id AND p.activo = TRUE) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'PELUQUERO_INACTIVO_O_INVALIDO';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.tamanos t WHERE t.id = p_tamano_id AND t.activo = TRUE) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'TAMANO_INACTIVO_O_INVALIDO';
    END IF;
    SELECT ps.duracion_minutos INTO v_duracion
    FROM public.precios_servicios ps
    WHERE ps.servicio_id = p_servicio_id
      AND ps.especie = v_mascota_anterior.especie
      AND ps.tamano_id = p_tamano_id
      AND ps.activo = TRUE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'CONFIGURACION_PRECIO_SERVICIO_NO_ENCONTRADA';
    END IF;

    UPDATE public.mascotas
    SET tamano_id = p_tamano_id
    WHERE id = v_mascota_anterior.id
    RETURNING * INTO v_mascota_nueva;

    UPDATE public.citas
    SET
        servicio_id = p_servicio_id,
        peluquero_id = p_peluquero_id,
        fin_programado = inicio_programado + MAKE_INTERVAL(mins => v_duracion),
        estado = 'atendida'
    WHERE id = p_cita_id
    RETURNING * INTO v_cita_nueva;

    INSERT INTO public.registros_servicio (
        cita_id, servicio_id, peluquero_id, tamano_id,
        heridas_visibles, raspones, piel_irritada, costras, inflamacion,
        cojera, dolor_al_tocar, pulgas, garrapatas, piojos,
        observaciones_ingreso, firma_ingreso_url,
        notas_servicio, estado, activo
    )
    VALUES (
        p_cita_id, p_servicio_id, p_peluquero_id, p_tamano_id,
        p_heridas_visibles, p_raspones, p_piel_irritada, p_costras, p_inflamacion,
        p_cojera, p_dolor_al_tocar, p_pulgas, p_garrapatas, p_piojos,
        COALESCE(p_observaciones_ingreso, ''), p_firma_ingreso_url,
        p_notas_servicio, 'en_progreso', TRUE
    )
    RETURNING * INTO v_registro;

    PERFORM petstore_private.auditar_cambio(
        'mascotas', v_mascota_nueva.id::TEXT, 'actualizar',
        TO_JSONB(v_mascota_anterior), TO_JSONB(v_mascota_nueva), NULL, NULL
    );
    PERFORM petstore_private.auditar_cambio(
        'citas', v_cita_nueva.id::TEXT, 'iniciar_atencion',
        TO_JSONB(v_cita_anterior), TO_JSONB(v_cita_nueva), v_cita_nueva.sucursal_id, NULL
    );
    PERFORM petstore_private.auditar_cambio(
        'registros_servicio', v_registro.id::TEXT, 'insertar',
        NULL, TO_JSONB(v_registro), v_cita_nueva.sucursal_id, NULL
    );

    RETURN v_registro;
EXCEPTION
    WHEN unique_violation THEN
        RAISE EXCEPTION USING ERRCODE = 'PC001', MESSAGE = 'CITA_YA_TIENE_REGISTRO_SERVICIO';
    WHEN foreign_key_violation OR check_violation OR not_null_violation THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'DATOS_INVALIDOS';
END;
$$;

CREATE FUNCTION public.registros_servicio_iniciar(
    p_cita_id BIGINT,
    p_servicio_id BIGINT,
    p_peluquero_id BIGINT,
    p_tamano_id BIGINT,
    p_heridas_visibles BOOLEAN,
    p_raspones BOOLEAN,
    p_piel_irritada BOOLEAN,
    p_costras BOOLEAN,
    p_inflamacion BOOLEAN,
    p_cojera BOOLEAN,
    p_dolor_al_tocar BOOLEAN,
    p_pulgas BOOLEAN,
    p_garrapatas BOOLEAN,
    p_piojos BOOLEAN,
    p_observaciones_ingreso TEXT,
    p_firma_ingreso_url TEXT,
    p_notas_servicio TEXT
)
RETURNS public.registros_servicio
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
    v_cita_anterior public.citas;
    v_cita_nueva public.citas;
    v_mascota_anterior public.mascotas;
    v_mascota_nueva public.mascotas;
    v_registro public.registros_servicio;
    v_duracion INTEGER;
BEGIN
    PERFORM petstore_private.requerir_usuario_activo();
    PERFORM petstore_private.establecer_actor();

    SELECT * INTO v_cita_anterior
    FROM public.citas
    WHERE id = p_cita_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'CITA_NO_ENCONTRADA';
    END IF;

    PERFORM petstore_private.requerir_acceso_sucursal(v_cita_anterior.sucursal_id);

    IF NOT EXISTS (
        SELECT 1 FROM public.sucursales s
        WHERE s.id = v_cita_anterior.sucursal_id AND s.activo = TRUE
    ) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'SUCURSAL_INACTIVA_O_INVALIDA';
    END IF;

    SELECT * INTO v_mascota_anterior
    FROM public.mascotas m
    WHERE m.id = v_cita_anterior.mascota_id
      AND m.activo = TRUE
      AND EXISTS (
          SELECT 1 FROM public.clientes c
          WHERE c.id = m.cliente_id AND c.activo = TRUE
      )
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'MASCOTA_INACTIVA_O_INVALIDA';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.servicios s WHERE s.id = p_servicio_id AND s.activo = TRUE) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'SERVICIO_INACTIVO_O_INVALIDO';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.peluqueros p WHERE p.id = p_peluquero_id AND p.activo = TRUE) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'PELUQUERO_INACTIVO_O_INVALIDO';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.tamanos t WHERE t.id = p_tamano_id AND t.activo = TRUE) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'TAMANO_INACTIVO_O_INVALIDO';
    END IF;
    SELECT ps.duracion_minutos INTO v_duracion
    FROM public.precios_servicios ps
    WHERE ps.servicio_id = p_servicio_id
      AND ps.especie = v_mascota_anterior.especie
      AND ps.tamano_id = p_tamano_id
      AND ps.activo = TRUE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'CONFIGURACION_PRECIO_SERVICIO_NO_ENCONTRADA';
    END IF;

    UPDATE public.mascotas
    SET tamano_id = p_tamano_id
    WHERE id = v_mascota_anterior.id
    RETURNING * INTO v_mascota_nueva;

    UPDATE public.citas
    SET
        servicio_id = p_servicio_id,
        peluquero_id = p_peluquero_id,
        fin_programado = inicio_programado + MAKE_INTERVAL(mins => v_duracion),
        estado = 'atendida'
    WHERE id = p_cita_id
    RETURNING * INTO v_cita_nueva;

    INSERT INTO public.registros_servicio (
        cita_id, servicio_id, peluquero_id, tamano_id,
        heridas_visibles, raspones, piel_irritada, costras, inflamacion,
        cojera, dolor_al_tocar, pulgas, garrapatas, piojos,
        observaciones_ingreso, firma_ingreso_url,
        notas_servicio, estado, activo
    )
    VALUES (
        p_cita_id, p_servicio_id, p_peluquero_id, p_tamano_id,
        p_heridas_visibles, p_raspones, p_piel_irritada, p_costras, p_inflamacion,
        p_cojera, p_dolor_al_tocar, p_pulgas, p_garrapatas, p_piojos,
        COALESCE(p_observaciones_ingreso, ''), p_firma_ingreso_url,
        p_notas_servicio, 'en_progreso', TRUE
    )
    RETURNING * INTO v_registro;

    PERFORM petstore_private.auditar_cambio(
        'mascotas', v_mascota_nueva.id::TEXT, 'actualizar',
        TO_JSONB(v_mascota_anterior), TO_JSONB(v_mascota_nueva), NULL, NULL
    );
    PERFORM petstore_private.auditar_cambio(
        'citas', v_cita_nueva.id::TEXT, 'iniciar_atencion',
        TO_JSONB(v_cita_anterior), TO_JSONB(v_cita_nueva), v_cita_nueva.sucursal_id, NULL
    );
    PERFORM petstore_private.auditar_cambio(
        'registros_servicio', v_registro.id::TEXT, 'insertar',
        NULL, TO_JSONB(v_registro), v_cita_nueva.sucursal_id, NULL
    );

    RETURN v_registro;
EXCEPTION
    WHEN unique_violation THEN
        RAISE EXCEPTION USING ERRCODE = 'PC001', MESSAGE = 'CITA_YA_TIENE_REGISTRO_SERVICIO';
    WHEN foreign_key_violation OR check_violation OR not_null_violation THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'DATOS_INVALIDOS';
END;
$$;

CREATE FUNCTION public.registros_servicio_actualizar(
    p_id BIGINT,
    p_servicio_id BIGINT,
    p_peluquero_id BIGINT,
    p_tamano_id BIGINT,
    p_cupon_id UUID,
    p_heridas_visibles BOOLEAN,
    p_raspones BOOLEAN,
    p_piel_irritada BOOLEAN,
    p_costras BOOLEAN,
    p_inflamacion BOOLEAN,
    p_cojera BOOLEAN,
    p_dolor_al_tocar BOOLEAN,
    p_pulgas BOOLEAN,
    p_garrapatas BOOLEAN,
    p_piojos BOOLEAN,
    p_observaciones_ingreso TEXT,
    p_firma_ingreso_url TEXT,
    p_firma_entrega_url TEXT,
    p_notas_servicio TEXT,
    p_calificacion_satisfaccion SMALLINT,
    p_comentario_satisfaccion TEXT,
    p_precio_base NUMERIC(10, 2),
    p_descuento_cupon NUMERIC(10, 2),
    p_monto_final NUMERIC(10, 2),
    p_monto_pagado NUMERIC(10, 2),
    p_activo BOOLEAN,
    p_pagos JSONB DEFAULT NULL,
    p_motivo TEXT DEFAULT NULL
)
RETURNS public.registros_servicio
LANGUAGE plpgsql SECURITY INVOKER SET search_path = ''
AS $$
DECLARE
    v_actor UUID;
    v_anterior public.registros_servicio;
    v_fila public.registros_servicio;
    v_cita_anterior public.citas;
    v_cita_nueva public.citas;
    v_mascota_anterior public.mascotas;
    v_mascota_nueva public.mascotas;
    v_precio NUMERIC(10, 2);
    v_suma NUMERIC(10, 2) := 0;
    v_pago RECORD;
    v_pagos_anteriores JSONB;
    v_pagos_nuevos JSONB;
    v_metodo_cupon_id BIGINT;
BEGIN
    v_actor := petstore_private.requerir_usuario_activo();
    PERFORM petstore_private.establecer_actor();

    SELECT rs.* INTO v_anterior
    FROM public.registros_servicio rs
    WHERE rs.id = p_id
    FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'REGISTRO_NO_ENCONTRADO'; END IF;

    SELECT * INTO v_cita_anterior FROM public.citas WHERE id = v_anterior.cita_id FOR UPDATE;
    PERFORM petstore_private.requerir_acceso_sucursal(v_cita_anterior.sucursal_id);
    SELECT * INTO v_mascota_anterior
    FROM public.mascotas WHERE id = v_cita_anterior.mascota_id FOR UPDATE;

    IF v_anterior.estado = 'completado' AND NOT petstore_private.es_admin_propietario() THEN
        RAISE EXCEPTION USING ERRCODE = 'PA001', MESSAGE = 'SOLO_ADMIN_PUEDE_EDITAR_COMPLETADO';
    END IF;
    IF v_anterior.estado = 'completado' AND p_pagos IS NULL THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'PAGOS_REQUERIDOS_PARA_COMPLETADO';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.servicios s WHERE s.id = p_servicio_id AND s.activo = TRUE) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'SERVICIO_INACTIVO_O_INVALIDO';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.peluqueros p WHERE p.id = p_peluquero_id AND p.activo = TRUE) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'PELUQUERO_INACTIVO_O_INVALIDO';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.tamanos t WHERE t.id = p_tamano_id AND t.activo = TRUE) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'TAMANO_INACTIVO_O_INVALIDO';
    END IF;

    IF p_precio_base IS NOT NULL THEN
        SELECT CASE WHEN v_anterior.usar_promocion THEN COALESCE(ps.precio_promocional, ps.precio) ELSE ps.precio END INTO v_precio
        FROM public.precios_servicios ps
        WHERE ps.servicio_id = p_servicio_id AND ps.especie = v_mascota_anterior.especie AND ps.tamano_id = p_tamano_id AND ps.activo = TRUE;
        IF NOT FOUND OR v_precio IS DISTINCT FROM p_precio_base THEN
            RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'PRECIO_BASE_NO_COINCIDE';
        END IF;
    ELSIF v_anterior.estado = 'completado' THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'PRECIO_BASE_REQUERIDO';
    END IF;

    IF p_descuento_cupon > p_precio_base + COALESCE((SELECT SUM(a.precio * a.cantidad) FROM public.registros_servicio_adicionales a WHERE a.registro_servicio_id = p_id AND a.activo = TRUE), 0) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'DESCUENTO_EXCEDE_SUBTOTAL';
    END IF;
    IF p_cupon_id IS NULL AND p_descuento_cupon <> 0 THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'DESCUENTO_REQUIERE_CUPON';
    END IF;
    IF p_monto_final <> p_precio_base + COALESCE((SELECT SUM(a.precio * a.cantidad) FROM public.registros_servicio_adicionales a WHERE a.registro_servicio_id = p_id AND a.activo = TRUE), 0) - p_descuento_cupon THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'MONTO_FINAL_INVALIDO';
    END IF;

    UPDATE public.registros_servicio
    SET
        servicio_id = p_servicio_id,
        peluquero_id = p_peluquero_id,
        tamano_id = p_tamano_id,
        cupon_id = p_cupon_id,
        heridas_visibles = p_heridas_visibles,
        raspones = p_raspones,
        piel_irritada = p_piel_irritada,
        costras = p_costras,
        inflamacion = p_inflamacion,
        cojera = p_cojera,
        dolor_al_tocar = p_dolor_al_tocar,
        pulgas = p_pulgas,
        garrapatas = p_garrapatas,
        piojos = p_piojos,
        observaciones_ingreso = COALESCE(p_observaciones_ingreso, ''),
        firma_ingreso_url = p_firma_ingreso_url,
        firma_entrega_url = p_firma_entrega_url,
        notas_servicio = p_notas_servicio,
        calificacion_satisfaccion = p_calificacion_satisfaccion,
        comentario_satisfaccion = p_comentario_satisfaccion,
        precio_base = p_precio_base,
        descuento_cupon = p_descuento_cupon,
        monto_final = p_monto_final,
        monto_pagado = p_monto_pagado,
        activo = p_activo
    WHERE id = p_id
    RETURNING * INTO v_fila;

    UPDATE public.citas
    SET servicio_id = p_servicio_id, peluquero_id = p_peluquero_id
    WHERE id = v_cita_anterior.id
    RETURNING * INTO v_cita_nueva;

    UPDATE public.mascotas
    SET tamano_id = p_tamano_id
    WHERE id = v_mascota_anterior.id
    RETURNING * INTO v_mascota_nueva;

    IF p_pagos IS NOT NULL THEN
        IF JSONB_TYPEOF(p_pagos) <> 'array' THEN
            RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'PAGOS_DEBE_SER_ARREGLO';
        END IF;
        IF v_actor IS NULL THEN
            RAISE EXCEPTION USING ERRCODE = 'PA001', MESSAGE = 'USUARIO_REQUERIDO';
        END IF;

        SELECT COALESCE(JSONB_AGG(TO_JSONB(p) ORDER BY p.creado_en, p.id), '[]'::JSONB)
        INTO v_pagos_anteriores
        FROM public.pagos p
        WHERE p.registro_servicio_id = p_id AND p.activo = TRUE;

        UPDATE public.pagos SET activo = FALSE
        WHERE registro_servicio_id = p_id AND activo = TRUE;

        IF p_monto_final = 0 THEN
            SELECT cs.metodo_pago_cupon_id INTO v_metodo_cupon_id
            FROM public.configuracion_sistema cs
            INNER JOIN public.metodos_pago mp ON mp.id = cs.metodo_pago_cupon_id AND mp.activo = TRUE
            WHERE cs.id = 1;
            IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'METODO_PAGO_CUPON_NO_ENCONTRADO'; END IF;
            INSERT INTO public.pagos(registro_servicio_id, metodo_pago_id, monto, creado_por_usuario_id, activo)
            VALUES (p_id, v_metodo_cupon_id, 0.00, v_actor, TRUE);
            v_suma := 0.00;
        ELSE
            FOR v_pago IN
                SELECT * FROM JSONB_TO_RECORDSET(p_pagos)
                AS x(metodo_pago_id BIGINT, monto NUMERIC(10, 2))
            LOOP
                IF v_pago.metodo_pago_id IS NULL OR v_pago.monto IS NULL OR v_pago.monto < 0 THEN
                    RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'PAGO_INVALIDO';
                END IF;
                IF NOT EXISTS (
                    SELECT 1 FROM public.metodos_pago mp
                    WHERE mp.id = v_pago.metodo_pago_id AND mp.activo = TRUE
                ) THEN
                    RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'METODO_PAGO_INACTIVO_O_INVALIDO';
                END IF;
                INSERT INTO public.pagos(registro_servicio_id, metodo_pago_id, monto, creado_por_usuario_id, activo)
                VALUES (p_id, v_pago.metodo_pago_id, v_pago.monto, v_actor, TRUE);
                v_suma := v_suma + v_pago.monto;
            END LOOP;
        END IF;

        IF v_suma <> p_monto_pagado THEN
            RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'MONTO_PAGADO_NO_COINCIDE';
        END IF;
        IF v_anterior.estado = 'completado' AND v_suma <> p_monto_final THEN
            RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'TOTAL_PAGOS_INVALIDO';
        END IF;

        SELECT COALESCE(JSONB_AGG(TO_JSONB(p) ORDER BY p.creado_en, p.id), '[]'::JSONB)
        INTO v_pagos_nuevos
        FROM public.pagos p
        WHERE p.registro_servicio_id = p_id AND p.activo = TRUE;

        PERFORM petstore_private.auditar_cambio(
            'pagos', p_id::TEXT, 'reemplazar_lista',
            JSONB_BUILD_OBJECT('pagos', v_pagos_anteriores),
            JSONB_BUILD_OBJECT('pagos', v_pagos_nuevos),
            v_cita_anterior.sucursal_id,
            p_motivo
        );
    END IF;

    PERFORM petstore_private.auditar_cambio(
        'registros_servicio', p_id::TEXT, 'actualizar',
        TO_JSONB(v_anterior), TO_JSONB(v_fila), v_cita_anterior.sucursal_id, p_motivo
    );
    PERFORM petstore_private.auditar_cambio(
        'citas', v_cita_nueva.id::TEXT, 'sincronizar_registro_servicio',
        TO_JSONB(v_cita_anterior), TO_JSONB(v_cita_nueva), v_cita_nueva.sucursal_id, p_motivo
    );
    PERFORM petstore_private.auditar_cambio(
        'mascotas', v_mascota_nueva.id::TEXT, 'actualizar',
        TO_JSONB(v_mascota_anterior), TO_JSONB(v_mascota_nueva), NULL, p_motivo
    );

    RETURN v_fila;
EXCEPTION
    WHEN unique_violation THEN
        RAISE EXCEPTION USING ERRCODE = 'PC001', MESSAGE = 'CONFLICTO_DE_DATOS';
    WHEN foreign_key_violation OR check_violation OR not_null_violation OR invalid_text_representation THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'DATOS_INVALIDOS';
END;
$$;

CREATE FUNCTION public.registros_servicio_completar(
    p_registro_servicio_id BIGINT,
    p_servicio_id BIGINT,
    p_peluquero_id BIGINT,
    p_tamano_id BIGINT,
    p_cupon_id UUID,
    p_firma_entrega_url TEXT,
    p_notas_servicio TEXT,
    p_calificacion_satisfaccion SMALLINT,
    p_comentario_satisfaccion TEXT,
    p_precio_base NUMERIC(10, 2),
    p_descuento_cupon NUMERIC(10, 2),
    p_monto_final NUMERIC(10, 2),
    p_monto_pagado NUMERIC(10, 2),
    p_pagos JSONB
)
RETURNS JSONB
LANGUAGE plpgsql SECURITY INVOKER SET search_path = ''
AS $$
DECLARE
    v_actor UUID;
    v_anterior public.registros_servicio;
    v_fila public.registros_servicio;
    v_cita_anterior public.citas;
    v_cita_nueva public.citas;
    v_mascota_anterior public.mascotas;
    v_mascota_nueva public.mascotas;
    v_precio NUMERIC(10, 2);
    v_pago RECORD;
    v_suma NUMERIC(10, 2) := 0;
    v_metodo_cupon_id BIGINT;
    v_pagos_anteriores JSONB;
    v_pagos_nuevos JSONB;
BEGIN
    v_actor := petstore_private.requerir_usuario_activo();
    PERFORM petstore_private.establecer_actor();
    PERFORM SET_CONFIG('app.flujo_registro_servicio', 'completar', TRUE);
    IF v_actor IS NULL THEN
        RAISE EXCEPTION USING ERRCODE = 'PA001', MESSAGE = 'USUARIO_REQUERIDO';
    END IF;

    SELECT * INTO v_anterior
    FROM public.registros_servicio
    WHERE id = p_registro_servicio_id
    FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'REGISTRO_NO_ENCONTRADO'; END IF;
    IF v_anterior.estado <> 'en_progreso' THEN
        RAISE EXCEPTION USING ERRCODE = 'PE001', MESSAGE = 'REGISTRO_NO_ESTA_EN_PROGRESO';
    END IF;

    SELECT * INTO v_cita_anterior FROM public.citas WHERE id = v_anterior.cita_id FOR UPDATE;
    PERFORM petstore_private.requerir_acceso_sucursal(v_cita_anterior.sucursal_id);
    SELECT * INTO v_mascota_anterior FROM public.mascotas WHERE id = v_cita_anterior.mascota_id FOR UPDATE;

    IF NOT EXISTS (SELECT 1 FROM public.servicios s WHERE s.id = p_servicio_id AND s.activo = TRUE) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'SERVICIO_INACTIVO_O_INVALIDO';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.peluqueros p WHERE p.id = p_peluquero_id AND p.activo = TRUE) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'PELUQUERO_INACTIVO_O_INVALIDO';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.tamanos t WHERE t.id = p_tamano_id AND t.activo = TRUE) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'TAMANO_INACTIVO_O_INVALIDO';
    END IF;

    SELECT CASE WHEN v_anterior.usar_promocion THEN COALESCE(ps.precio_promocional, ps.precio) ELSE ps.precio END INTO v_precio
    FROM public.precios_servicios ps
    WHERE ps.servicio_id = p_servicio_id AND ps.especie = v_mascota_anterior.especie AND ps.tamano_id = p_tamano_id AND ps.activo = TRUE;
    IF NOT FOUND OR v_precio IS DISTINCT FROM p_precio_base THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'PRECIO_BASE_NO_COINCIDE';
    END IF;

    IF p_descuento_cupon > p_precio_base + COALESCE((SELECT SUM(a.precio * a.cantidad) FROM public.registros_servicio_adicionales a WHERE a.registro_servicio_id = p_registro_servicio_id AND a.activo = TRUE), 0) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'DESCUENTO_EXCEDE_SUBTOTAL';
    END IF;
    IF p_cupon_id IS NULL AND p_descuento_cupon <> 0 THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'DESCUENTO_REQUIERE_CUPON';
    END IF;
    IF p_monto_final <> p_precio_base + COALESCE((SELECT SUM(a.precio * a.cantidad) FROM public.registros_servicio_adicionales a WHERE a.registro_servicio_id = p_registro_servicio_id AND a.activo = TRUE), 0) - p_descuento_cupon THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'MONTO_FINAL_INVALIDO';
    END IF;
    IF p_monto_pagado <> p_monto_final THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'MONTO_PAGADO_NO_COINCIDE';
    END IF;
    IF p_pagos IS NULL OR JSONB_TYPEOF(p_pagos) <> 'array' THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'PAGOS_DEBE_SER_ARREGLO';
    END IF;

    SELECT COALESCE(JSONB_AGG(TO_JSONB(p) ORDER BY p.creado_en, p.id), '[]'::JSONB)
    INTO v_pagos_anteriores
    FROM public.pagos p
    WHERE p.registro_servicio_id = p_registro_servicio_id AND p.activo = TRUE;

    UPDATE public.pagos SET activo = FALSE
    WHERE registro_servicio_id = p_registro_servicio_id AND activo = TRUE;

    IF p_monto_final = 0 THEN
        SELECT cs.metodo_pago_cupon_id INTO v_metodo_cupon_id
        FROM public.configuracion_sistema cs
        INNER JOIN public.metodos_pago mp ON mp.id = cs.metodo_pago_cupon_id AND mp.activo = TRUE
        WHERE cs.id = 1;
        IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'METODO_PAGO_CUPON_NO_ENCONTRADO'; END IF;
        INSERT INTO public.pagos(registro_servicio_id, metodo_pago_id, monto, creado_por_usuario_id, activo)
        VALUES (p_registro_servicio_id, v_metodo_cupon_id, 0.00, v_actor, TRUE);
        v_suma := 0.00;
    ELSE
        FOR v_pago IN
            SELECT * FROM JSONB_TO_RECORDSET(p_pagos)
            AS x(metodo_pago_id BIGINT, monto NUMERIC(10, 2))
        LOOP
            IF v_pago.metodo_pago_id IS NULL OR v_pago.monto IS NULL OR v_pago.monto < 0 THEN
                RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'PAGO_INVALIDO';
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM public.metodos_pago mp
                WHERE mp.id = v_pago.metodo_pago_id AND mp.activo = TRUE
            ) THEN
                RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'METODO_PAGO_INACTIVO_O_INVALIDO';
            END IF;
            INSERT INTO public.pagos(registro_servicio_id, metodo_pago_id, monto, creado_por_usuario_id, activo)
            VALUES (p_registro_servicio_id, v_pago.metodo_pago_id, v_pago.monto, v_actor, TRUE);
            v_suma := v_suma + v_pago.monto;
        END LOOP;
    END IF;

    IF v_suma <> p_monto_final OR v_suma <> p_monto_pagado THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'TOTAL_PAGOS_INVALIDO';
    END IF;

    UPDATE public.registros_servicio
    SET
        servicio_id = p_servicio_id,
        peluquero_id = p_peluquero_id,
        tamano_id = p_tamano_id,
        cupon_id = p_cupon_id,
        firma_entrega_url = p_firma_entrega_url,
        notas_servicio = p_notas_servicio,
        calificacion_satisfaccion = p_calificacion_satisfaccion,
        comentario_satisfaccion = p_comentario_satisfaccion,
        precio_base = p_precio_base,
        descuento_cupon = p_descuento_cupon,
        monto_final = p_monto_final,
        monto_pagado = p_monto_pagado,
        estado = 'completado'
    WHERE id = p_registro_servicio_id
    RETURNING * INTO v_fila;

    UPDATE public.citas
    SET servicio_id = p_servicio_id, peluquero_id = p_peluquero_id
    WHERE id = v_cita_anterior.id
    RETURNING * INTO v_cita_nueva;

    UPDATE public.mascotas
    SET tamano_id = p_tamano_id
    WHERE id = v_mascota_anterior.id
    RETURNING * INTO v_mascota_nueva;

    SELECT COALESCE(JSONB_AGG(TO_JSONB(p) ORDER BY p.creado_en, p.id), '[]'::JSONB)
    INTO v_pagos_nuevos
    FROM public.pagos p
    WHERE p.registro_servicio_id = p_registro_servicio_id AND p.activo = TRUE;

    PERFORM petstore_private.auditar_cambio(
        'registros_servicio', p_registro_servicio_id::TEXT, 'completar',
        TO_JSONB(v_anterior), TO_JSONB(v_fila), v_cita_anterior.sucursal_id, NULL
    );
    PERFORM petstore_private.auditar_cambio(
        'pagos', p_registro_servicio_id::TEXT, 'reemplazar_lista',
        JSONB_BUILD_OBJECT('pagos', v_pagos_anteriores),
        JSONB_BUILD_OBJECT('pagos', v_pagos_nuevos),
        v_cita_anterior.sucursal_id, NULL
    );
    PERFORM petstore_private.auditar_cambio(
        'citas', v_cita_nueva.id::TEXT, 'sincronizar_registro_servicio',
        TO_JSONB(v_cita_anterior), TO_JSONB(v_cita_nueva), v_cita_nueva.sucursal_id, NULL
    );
    PERFORM petstore_private.auditar_cambio(
        'mascotas', v_mascota_nueva.id::TEXT, 'actualizar',
        TO_JSONB(v_mascota_anterior), TO_JSONB(v_mascota_nueva), NULL, NULL
    );

    RETURN JSONB_BUILD_OBJECT(
        'registro_servicio', TO_JSONB(v_fila),
        'cita', TO_JSONB(v_cita_nueva),
        'mascota', TO_JSONB(v_mascota_nueva),
        'pagos', v_pagos_nuevos
    );
EXCEPTION
    WHEN unique_violation THEN
        RAISE EXCEPTION USING ERRCODE = 'PC001', MESSAGE = 'CONFLICTO_DE_DATOS';
    WHEN foreign_key_violation OR check_violation OR not_null_violation OR invalid_text_representation THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'DATOS_INVALIDOS';
END;
$$;

CREATE OR REPLACE FUNCTION public.preparar_registro_servicio()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_foto_ingreso_requerida BOOLEAN;
    v_foto_egreso_requerida BOOLEAN;
    v_cliente_id BIGINT;
    v_cupon public.cupones%ROWTYPE;
    v_cupon_ya_vinculado_al_mismo_registro BOOLEAN := FALSE;
    v_transicion_a_completado BOOLEAN;
BEGIN
    -- Signature timestamps are assigned only the first time each signature is populated.
    IF TG_OP = 'INSERT' THEN
        IF NEW.firma_ingreso_url IS NOT NULL THEN
            NEW.firma_ingreso_en := CURRENT_TIMESTAMP;
        ELSE
            NEW.firma_ingreso_en := NULL;
        END IF;

        IF NEW.firma_entrega_url IS NOT NULL THEN
            NEW.firma_entrega_en := CURRENT_TIMESTAMP;
        ELSE
            NEW.firma_entrega_en := NULL;
        END IF;
    ELSE
        IF OLD.firma_ingreso_en IS NOT NULL THEN
            NEW.firma_ingreso_en := OLD.firma_ingreso_en;
        ELSIF NEW.firma_ingreso_url IS NOT NULL THEN
            NEW.firma_ingreso_en := CURRENT_TIMESTAMP;
        ELSE
            NEW.firma_ingreso_en := NULL;
        END IF;

        IF OLD.firma_entrega_en IS NOT NULL THEN
            NEW.firma_entrega_en := OLD.firma_entrega_en;
        ELSIF NEW.firma_entrega_url IS NOT NULL THEN
            NEW.firma_entrega_en := CURRENT_TIMESTAMP;
        ELSE
            NEW.firma_entrega_en := NULL;
        END IF;
    END IF;

    v_transicion_a_completado :=
        NEW.estado = 'completado'
        AND (
            TG_OP = 'INSERT'
            OR OLD.estado IS DISTINCT FROM 'completado'
        );

    -- fin_real is assigned on the first completion and is never overwritten.
    IF TG_OP = 'UPDATE' AND OLD.fin_real IS NOT NULL THEN
        NEW.fin_real := OLD.fin_real;
    ELSIF v_transicion_a_completado THEN
        NEW.fin_real := CURRENT_TIMESTAMP;
    END IF;

    IF v_transicion_a_completado THEN
        SELECT foto_antes_requerida, foto_despues_requerida
        INTO STRICT v_foto_ingreso_requerida, v_foto_egreso_requerida
        FROM public.configuracion_sistema
        WHERE id = 1;

        IF v_foto_ingreso_requerida AND NOT EXISTS (
            SELECT 1 FROM public.registros_servicio_fotos
            WHERE registro_servicio_id = NEW.id AND momento = 'ingreso'
        ) THEN
            RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'FOTO_INGRESO_REQUERIDA';
        END IF;
        IF v_foto_egreso_requerida AND NOT EXISTS (
            SELECT 1 FROM public.registros_servicio_fotos
            WHERE registro_servicio_id = NEW.id AND momento = 'egreso'
        ) THEN
            RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'FOTO_EGRESO_REQUERIDA';
        END IF;

        IF NEW.cupon_id IS NOT NULL THEN
            SELECT *
            INTO v_cupon
            FROM public.cupones c
            WHERE c.id = NEW.cupon_id
            FOR UPDATE;

            IF NOT FOUND THEN
                RAISE EXCEPTION 'El cupón indicado no existe';
            END IF;

            SELECT m.cliente_id
            INTO v_cliente_id
            FROM public.citas c
            INNER JOIN public.mascotas m ON m.id = c.mascota_id
            WHERE c.id = NEW.cita_id;

            IF v_cupon.cliente_id <> v_cliente_id THEN
                RAISE EXCEPTION 'El cupón no pertenece al cliente de la mascota atendida';
            END IF;

            IF v_cupon.servicio_id <> NEW.servicio_id THEN
                RAISE EXCEPTION 'El cupón no corresponde al servicio realizado';
            END IF;

            v_cupon_ya_vinculado_al_mismo_registro :=
                TG_OP = 'UPDATE'
                AND OLD.cupon_id IS NOT DISTINCT FROM NEW.cupon_id
                AND OLD.cupon_id IS NOT NULL;

            IF v_cupon.canjeado_en IS NOT NULL THEN
                IF NOT v_cupon_ya_vinculado_al_mismo_registro THEN
                    RAISE EXCEPTION 'El cupón ya fue canjeado en otro servicio';
                END IF;
            ELSE
                IF v_cupon.activo = FALSE THEN
                    RAISE EXCEPTION 'El cupón está inactivo';
                END IF;

                IF v_cupon.fecha_expiracion
                   < (CURRENT_TIMESTAMP AT TIME ZONE 'America/Guatemala')::DATE THEN
                    RAISE EXCEPTION 'El cupón está vencido';
                END IF;

                UPDATE public.cupones
                SET
                    canjeado_en = CURRENT_TIMESTAMP,
                    activo = FALSE
                WHERE id = NEW.cupon_id;
            END IF;
        END IF;
    END IF;

    RETURN NEW;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE EXCEPTION 'Debe existir la fila id = 1 en configuracion_sistema';
END;
$$;

ALTER TABLE public.registros_servicio
    DROP COLUMN foto_antes_url,
    DROP COLUMN foto_antes_subida_en,
    DROP COLUMN foto_despues_url,
    DROP COLUMN foto_despues_subida_en;

DO $$
DECLARE v_funcion RECORD;
BEGIN
    FOR v_funcion IN
        SELECT n.nspname AS esquema, p.proname AS nombre,
               PG_GET_FUNCTION_IDENTITY_ARGUMENTS(p.oid) AS argumentos
        FROM pg_proc p
        INNER JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = 'public'
          AND p.proname IN (
              'registros_servicio_insertar',
              'registros_servicio_iniciar',
              'registros_servicio_actualizar',
              'registros_servicio_completar'
          )
    LOOP
        EXECUTE FORMAT('REVOKE ALL ON FUNCTION %I.%I(%s) FROM PUBLIC, anon', v_funcion.esquema, v_funcion.nombre, v_funcion.argumentos);
        EXECUTE FORMAT('GRANT EXECUTE ON FUNCTION %I.%I(%s) TO authenticated, service_role', v_funcion.esquema, v_funcion.nombre, v_funcion.argumentos);
    END LOOP;
END;
$$;


COMMIT;
