CREATE TABLE public.paquetes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL CHECK (BTRIM(nombre) <> ''),
    precio NUMERIC(10, 2) NOT NULL CHECK (precio > 0),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_por_usuario_id UUID NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_paquetes_nombre_lower ON public.paquetes (LOWER(nombre));

CREATE TABLE public.paquetes_servicios (
    paquete_id BIGINT NOT NULL REFERENCES public.paquetes(id) ON DELETE CASCADE,
    servicio_id BIGINT NOT NULL REFERENCES public.servicios(id) ON DELETE RESTRICT,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (paquete_id, servicio_id)
);

CREATE TABLE public.paquetes_asignaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paquete_id BIGINT NOT NULL REFERENCES public.paquetes(id) ON DELETE RESTRICT,
    cliente_id BIGINT NOT NULL REFERENCES public.clientes(id) ON DELETE RESTRICT,
    precio_pagado NUMERIC(10, 2) NOT NULL CHECK (precio_pagado > 0),
    asignado_por_usuario_id UUID NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
    asignado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_paquetes_asignaciones_cliente ON public.paquetes_asignaciones (cliente_id, asignado_en DESC);
CREATE INDEX ix_paquetes_asignaciones_paquete ON public.paquetes_asignaciones (paquete_id, asignado_en DESC);

ALTER TABLE public.cupones
    ADD COLUMN paquete_asignacion_id BIGINT NULL
        REFERENCES public.paquetes_asignaciones(id) ON DELETE RESTRICT;

ALTER TABLE public.cupones
    DROP CONSTRAINT IF EXISTS cupones_origen_valido,
    ADD CONSTRAINT cupones_origen_valido CHECK (origen IN ('manual', 'automatico', 'paquete')),
    ADD CONSTRAINT cupones_paquete_validos CHECK (
        origen <> 'paquete'
        OR (
            cliente_id IS NOT NULL
            AND servicio_id IS NOT NULL
            AND tipo_descuento = 'porcentaje'
            AND valor = 100
            AND uso_unico = TRUE
            AND paquete_asignacion_id IS NOT NULL
        )
    );

CREATE INDEX ix_cupones_paquete_asignacion ON public.cupones (paquete_asignacion_id, servicio_id, activo);

ALTER TABLE public.paquetes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.paquetes_servicios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.paquetes_asignaciones ENABLE ROW LEVEL SECURITY;

CREATE POLICY paquetes_select
ON public.paquetes FOR SELECT TO authenticated
USING ((SELECT petstore_private.es_admin_propietario()));

CREATE POLICY paquetes_insert
ON public.paquetes FOR INSERT TO authenticated
WITH CHECK ((SELECT petstore_private.es_admin_propietario()));

CREATE POLICY paquetes_update
ON public.paquetes FOR UPDATE TO authenticated
USING ((SELECT petstore_private.es_admin_propietario()))
WITH CHECK ((SELECT petstore_private.es_admin_propietario()));

CREATE POLICY paquetes_delete
ON public.paquetes FOR DELETE TO authenticated
USING ((SELECT petstore_private.es_admin_propietario()));

CREATE POLICY paquetes_servicios_select
ON public.paquetes_servicios FOR SELECT TO authenticated
USING ((SELECT petstore_private.es_admin_propietario()));

CREATE POLICY paquetes_servicios_insert
ON public.paquetes_servicios FOR INSERT TO authenticated
WITH CHECK ((SELECT petstore_private.es_admin_propietario()));

CREATE POLICY paquetes_asignaciones_select
ON public.paquetes_asignaciones FOR SELECT TO authenticated
USING ((SELECT petstore_private.es_admin_propietario()));

CREATE POLICY paquetes_asignaciones_insert
ON public.paquetes_asignaciones FOR INSERT TO authenticated
WITH CHECK ((SELECT petstore_private.es_admin_propietario()));

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
    public.paquetes,
    public.paquetes_servicios,
    public.paquetes_asignaciones
TO authenticated;

GRANT ALL PRIVILEGES ON TABLE
    public.paquetes,
    public.paquetes_servicios,
    public.paquetes_asignaciones
TO service_role;

GRANT USAGE, SELECT, UPDATE ON SEQUENCE
    public.paquetes_id_seq,
    public.paquetes_asignaciones_id_seq
TO authenticated, service_role;

CREATE FUNCTION public.paquetes_crear(
    p_nombre TEXT,
    p_precio NUMERIC(10, 2),
    p_servicios JSONB
)
RETURNS public.paquetes
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
    v_actor UUID;
    v_paquete public.paquetes;
    v_item RECORD;
BEGIN
    v_actor := petstore_private.requerir_admin_propietario();
    PERFORM petstore_private.establecer_actor();

    IF BTRIM(COALESCE(p_nombre, '')) = ''
       OR p_precio IS NULL
       OR p_precio <= 0
       OR p_servicios IS NULL
       OR COALESCE(JSONB_TYPEOF(p_servicios), '') <> 'array'
       OR JSONB_ARRAY_LENGTH(CASE WHEN JSONB_TYPEOF(p_servicios) = 'array' THEN p_servicios ELSE '[]'::JSONB END) = 0 THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'DATOS_INVALIDOS';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM JSONB_TO_RECORDSET(p_servicios) AS x(servicio_id BIGINT, cantidad INTEGER)
        WHERE servicio_id IS NULL OR cantidad IS NULL OR cantidad < 1
    ) OR (
        SELECT COUNT(*) FROM JSONB_TO_RECORDSET(p_servicios) AS x(servicio_id BIGINT, cantidad INTEGER)
    ) <> (
        SELECT COUNT(DISTINCT servicio_id) FROM JSONB_TO_RECORDSET(p_servicios) AS x(servicio_id BIGINT, cantidad INTEGER)
    ) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'SERVICIOS_DEL_PAQUETE_INVALIDOS';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM JSONB_TO_RECORDSET(p_servicios) AS x(servicio_id BIGINT, cantidad INTEGER)
        LEFT JOIN public.servicios s ON s.id = x.servicio_id
        WHERE s.id IS NULL OR s.activo = FALSE OR s.es_adicional = TRUE
    ) THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'SERVICIO_DEL_PAQUETE_INVALIDO';
    END IF;

    INSERT INTO public.paquetes (nombre, precio, creado_por_usuario_id)
    VALUES (BTRIM(p_nombre), p_precio, v_actor)
    RETURNING * INTO v_paquete;

    FOR v_item IN
        SELECT * FROM JSONB_TO_RECORDSET(p_servicios) AS x(servicio_id BIGINT, cantidad INTEGER)
    LOOP
        INSERT INTO public.paquetes_servicios (paquete_id, servicio_id, cantidad)
        VALUES (v_paquete.id, v_item.servicio_id, v_item.cantidad);
    END LOOP;

    PERFORM petstore_private.auditar_cambio(
        'paquetes',
        v_paquete.id::TEXT,
        'insertar',
        NULL,
        TO_JSONB(v_paquete) || JSONB_BUILD_OBJECT('servicios', p_servicios),
        NULL,
        NULL
    );

    RETURN v_paquete;
EXCEPTION
    WHEN unique_violation THEN
        RAISE EXCEPTION USING ERRCODE = 'PC001', MESSAGE = 'PAQUETE_YA_EXISTE';
    WHEN check_violation OR foreign_key_violation OR not_null_violation THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'DATOS_INVALIDOS';
END;
$$;

CREATE FUNCTION public.paquetes_listar()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE v_resultado JSONB;
BEGIN
    PERFORM petstore_private.requerir_admin_propietario();

    SELECT COALESCE(JSONB_AGG(
        JSONB_BUILD_OBJECT(
            'id', p.id,
            'nombre', p.nombre,
            'precio', p.precio,
            'activo', p.activo,
            'creado_por_usuario_id', p.creado_por_usuario_id,
            'creado_en', p.creado_en,
            'servicios', COALESCE((
                SELECT JSONB_AGG(JSONB_BUILD_OBJECT(
                    'servicio_id', ps.servicio_id,
                    'servicio_nombre', s.nombre,
                    'cantidad', ps.cantidad
                ) ORDER BY s.nombre)
                FROM public.paquetes_servicios ps
                INNER JOIN public.servicios s ON s.id = ps.servicio_id
                WHERE ps.paquete_id = p.id
            ), '[]'::JSONB),
            'asignaciones', COALESCE((
                SELECT JSONB_AGG(JSONB_BUILD_OBJECT(
                    'id', pa.id,
                    'cliente_id', pa.cliente_id,
                    'cliente_nombre', c.nombre,
                    'precio_pagado', pa.precio_pagado,
                    'asignado_por_usuario_id', pa.asignado_por_usuario_id,
                    'asignado_en', pa.asignado_en
                ) ORDER BY pa.asignado_en DESC, pa.id DESC)
                FROM public.paquetes_asignaciones pa
                INNER JOIN public.clientes c ON c.id = pa.cliente_id
                WHERE pa.paquete_id = p.id
            ), '[]'::JSONB)
        ) ORDER BY p.activo DESC, p.creado_en DESC, p.id DESC
    ), '[]'::JSONB)
    INTO v_resultado
    FROM public.paquetes p;

    RETURN v_resultado;
END;
$$;

CREATE FUNCTION public.paquetes_asignar(
    p_paquete_id BIGINT,
    p_cliente_id BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
    v_actor UUID;
    v_paquete public.paquetes;
    v_cliente public.clientes;
    v_asignacion public.paquetes_asignaciones;
    v_item RECORD;
    v_coupon_index INTEGER;
    v_coupon_id UUID;
    v_cupones_generados INTEGER := 0;
BEGIN
    v_actor := petstore_private.requerir_admin_propietario();
    PERFORM petstore_private.establecer_actor();

    SELECT * INTO v_paquete
    FROM public.paquetes
    WHERE id = p_paquete_id
    FOR UPDATE;
    IF NOT FOUND OR NOT v_paquete.activo THEN
        RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'PAQUETE_NO_ENCONTRADO';
    END IF;

    SELECT * INTO v_cliente
    FROM public.clientes
    WHERE id = p_cliente_id AND activo = TRUE
    FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'CLIENTE_NO_ENCONTRADO';
    END IF;

    INSERT INTO public.paquetes_asignaciones (
        paquete_id, cliente_id, precio_pagado, asignado_por_usuario_id
    )
    VALUES (v_paquete.id, v_cliente.id, v_paquete.precio, v_actor)
    RETURNING * INTO v_asignacion;

    FOR v_item IN
        SELECT ps.servicio_id, ps.cantidad, s.nombre AS servicio_nombre
        FROM public.paquetes_servicios ps
        INNER JOIN public.servicios s ON s.id = ps.servicio_id
        WHERE ps.paquete_id = v_paquete.id
    LOOP
        FOR v_coupon_index IN 1..v_item.cantidad
        LOOP
            v_coupon_id := GEN_RANDOM_UUID();
            INSERT INTO public.cupones (
                id, nombre, cliente_id, servicio_id, tipo_descuento, valor,
                fecha_expiracion, activo, uso_unico, origen,
                paquete_asignacion_id, creado_por_usuario_id
            )
            VALUES (
                v_coupon_id,
                v_paquete.nombre || ' · ' || v_item.servicio_nombre,
                v_cliente.id,
                v_item.servicio_id,
                'porcentaje',
                100,
                NULL,
                TRUE,
                TRUE,
                'paquete',
                v_asignacion.id,
                v_actor
            );
            v_cupones_generados := v_cupones_generados + 1;
        END LOOP;
    END LOOP;

    PERFORM petstore_private.auditar_cambio(
        'paquete_asignacion',
        v_asignacion.id::TEXT,
        'asignar',
        NULL,
        TO_JSONB(v_asignacion) || JSONB_BUILD_OBJECT(
            'paquete_nombre', v_paquete.nombre,
            'cliente_nombre', v_cliente.nombre,
            'cupones_generados', v_cupones_generados
        ),
        NULL,
        NULL
    );

    RETURN JSONB_BUILD_OBJECT(
        'asignacion', TO_JSONB(v_asignacion),
        'cupones_generados', v_cupones_generados
    );
EXCEPTION
    WHEN check_violation OR foreign_key_violation OR not_null_violation THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'DATOS_INVALIDOS';
END;
$$;

CREATE OR REPLACE FUNCTION public.cupones_actualizar(
    p_id UUID,
    p_nombre TEXT,
    p_cliente_id BIGINT,
    p_servicio_id BIGINT,
    p_tipo_descuento public.tipo_descuento_cupon,
    p_valor NUMERIC(10, 2),
    p_fecha_expiracion DATE,
    p_uso_unico BOOLEAN,
    p_activo BOOLEAN
)
RETURNS public.cupones
LANGUAGE plpgsql SECURITY INVOKER SET search_path = ''
AS $$
DECLARE
    v_anterior public.cupones;
    v_fila public.cupones;
BEGIN
    PERFORM petstore_private.requerir_admin_propietario();
    PERFORM petstore_private.establecer_actor();

    SELECT * INTO v_anterior FROM public.cupones WHERE id = p_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'REGISTRO_NO_ENCONTRADO';
    END IF;
    IF v_anterior.canjeado_en IS NOT NULL OR v_anterior.origen = 'paquete' THEN
        RAISE EXCEPTION USING ERRCODE = 'PE001', MESSAGE = 'CUPON_NO_MODIFICABLE';
    END IF;
    IF p_fecha_expiracion IS NOT NULL
       AND p_fecha_expiracion < (CLOCK_TIMESTAMP() AT TIME ZONE 'America/Guatemala')::DATE THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'FECHA_EXPIRACION_INVALIDA';
    END IF;

    UPDATE public.cupones
    SET nombre = BTRIM(p_nombre), cliente_id = p_cliente_id, servicio_id = p_servicio_id,
        tipo_descuento = p_tipo_descuento, valor = p_valor,
        fecha_expiracion = p_fecha_expiracion, uso_unico = p_uso_unico, activo = p_activo
    WHERE id = p_id
    RETURNING * INTO v_fila;

    PERFORM petstore_private.auditar_cambio('cupones', p_id::TEXT, 'actualizar', TO_JSONB(v_anterior), TO_JSONB(v_fila), NULL, NULL);
    RETURN v_fila;
EXCEPTION
    WHEN foreign_key_violation OR check_violation OR not_null_violation THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'DATOS_INVALIDOS';
END;
$$;

CREATE OR REPLACE FUNCTION public.cupones_eliminar(p_id UUID)
RETURNS public.cupones
LANGUAGE plpgsql SECURITY INVOKER SET search_path = ''
AS $$
DECLARE v_anterior public.cupones; v_fila public.cupones;
BEGIN
    PERFORM petstore_private.requerir_admin_propietario();
    PERFORM petstore_private.establecer_actor();
    SELECT * INTO v_anterior FROM public.cupones WHERE id = p_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'REGISTRO_NO_ENCONTRADO'; END IF;
    IF v_anterior.origen = 'paquete' THEN RAISE EXCEPTION USING ERRCODE = 'PE001', MESSAGE = 'CUPON_NO_MODIFICABLE'; END IF;
    UPDATE public.cupones SET activo = FALSE WHERE id = p_id RETURNING * INTO v_fila;
    PERFORM petstore_private.auditar_cambio('cupones', p_id::TEXT, 'eliminar_logico', TO_JSONB(v_anterior), TO_JSONB(v_fila), NULL, NULL);
    RETURN v_fila;
END;
$$;

REVOKE ALL ON FUNCTION public.paquetes_crear(TEXT, NUMERIC, JSONB) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.paquetes_listar() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.paquetes_asignar(BIGINT, BIGINT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.paquetes_crear(TEXT, NUMERIC, JSONB) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.paquetes_listar() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.paquetes_asignar(BIGINT, BIGINT) TO authenticated, service_role;
