BEGIN;

CREATE TABLE public.notificaciones_email (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_servicio_id BIGINT NOT NULL
        REFERENCES public.registros_servicio(id) ON DELETE RESTRICT,
    cita_id BIGINT NOT NULL
        REFERENCES public.citas(id) ON DELETE RESTRICT,
    cliente_id BIGINT NOT NULL
        REFERENCES public.clientes(id) ON DELETE RESTRICT,
    tipo_notificacion TEXT NOT NULL DEFAULT 'service_completed'
        CHECK (tipo_notificacion = 'service_completed'),
    destinatario TEXT NULL
        CHECK (destinatario IS NULL OR destinatario ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
    proveedor TEXT NOT NULL DEFAULT 'gmail',
    estado TEXT NOT NULL DEFAULT 'pending'
        CHECK (estado IN ('pending', 'sent', 'failed')),
    intentos INTEGER NOT NULL DEFAULT 0 CHECK (intentos >= 0),
    proveedor_mensaje_id TEXT NULL,
    ultimo_error TEXT NULL,
    enviado_en TIMESTAMPTZ NULL,
    procesando_token UUID NULL,
    procesando_en TIMESTAMPTZ NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (registro_servicio_id, tipo_notificacion)
);

CREATE INDEX ix_notificaciones_email_creado_en
    ON public.notificaciones_email (creado_en DESC, id DESC);
CREATE INDEX ix_notificaciones_email_estado_creado_en
    ON public.notificaciones_email (estado, creado_en DESC, id DESC);
CREATE INDEX ix_notificaciones_email_cliente_creado_en
    ON public.notificaciones_email (cliente_id, creado_en DESC, id DESC);

ALTER TABLE public.notificaciones_email ENABLE ROW LEVEL SECURITY;

CREATE POLICY notificaciones_email_select
ON public.notificaciones_email FOR SELECT TO authenticated
USING (
    (SELECT petstore_private.usuario_activo())
    AND EXISTS (
        SELECT 1
        FROM public.citas c
        WHERE c.id = cita_id
          AND (SELECT petstore_private.tiene_acceso_sucursal(c.sucursal_id))
    )
);

REVOKE ALL PRIVILEGES ON TABLE public.notificaciones_email FROM anon, authenticated;
GRANT SELECT ON TABLE public.notificaciones_email TO authenticated;
GRANT ALL PRIVILEGES ON TABLE public.notificaciones_email TO service_role;
REVOKE ALL PRIVILEGES ON SEQUENCE public.notificaciones_email_id_seq FROM anon, authenticated;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.notificaciones_email_id_seq TO service_role;

CREATE FUNCTION public.notificaciones_email_servicio_completado_preparar(
    p_registro_servicio_id BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
    v_registro public.registros_servicio;
    v_cita public.citas;
    v_cliente public.clientes;
    v_mascota public.mascotas;
    v_sucursal public.sucursales;
    v_servicio public.servicios;
    v_id BIGINT;
    v_creada BOOLEAN := FALSE;
BEGIN
    PERFORM petstore_private.requerir_usuario_activo();

    SELECT * INTO v_registro
    FROM public.registros_servicio
    WHERE id = p_registro_servicio_id;
    IF NOT FOUND OR v_registro.estado <> 'completado' THEN
        RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'REGISTRO_NO_ENCONTRADO';
    END IF;

    SELECT * INTO v_cita FROM public.citas WHERE id = v_registro.cita_id;
    PERFORM petstore_private.requerir_acceso_sucursal(v_cita.sucursal_id);
    SELECT * INTO v_mascota FROM public.mascotas WHERE id = v_cita.mascota_id;
    SELECT * INTO v_cliente FROM public.clientes WHERE id = v_mascota.cliente_id;
    SELECT * INTO v_sucursal FROM public.sucursales WHERE id = v_cita.sucursal_id;
    SELECT * INTO v_servicio FROM public.servicios WHERE id = v_registro.servicio_id;

    INSERT INTO public.notificaciones_email (
        registro_servicio_id,
        cita_id,
        cliente_id,
        destinatario,
        estado,
        ultimo_error
    )
    VALUES (
        v_registro.id,
        v_cita.id,
        v_mascota.cliente_id,
        NULLIF(BTRIM(v_cliente.email), ''),
        CASE
            WHEN v_cliente.email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' THEN 'pending'
            ELSE 'failed'
        END,
        CASE
            WHEN v_cliente.email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' THEN NULL
            ELSE 'recipient_email_missing'
        END
    )
    ON CONFLICT (registro_servicio_id, tipo_notificacion) DO NOTHING
    RETURNING id INTO v_id;
    v_creada := v_id IS NOT NULL;

    IF NOT v_creada THEN
        SELECT id INTO v_id
        FROM public.notificaciones_email
        WHERE registro_servicio_id = v_registro.id
          AND tipo_notificacion = 'service_completed';
    END IF;

    RETURN (
        SELECT TO_JSONB(n) || JSONB_BUILD_OBJECT(
            'creada', v_creada,
            'cliente_nombre', v_cliente.nombre,
            'mascota_nombre', v_mascota.nombre,
            'sucursal_nombre', v_sucursal.nombre,
            'servicio_nombre', v_servicio.nombre
        )
        FROM public.notificaciones_email n
        WHERE n.id = v_id
    );
END;
$$;

CREATE FUNCTION public.notificaciones_email_reclamar_pendiente(
    p_id BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
    v_sucursal_id BIGINT;
    v_token UUID;
BEGIN
    PERFORM petstore_private.requerir_usuario_activo();
    SELECT c.sucursal_id INTO v_sucursal_id
    FROM public.notificaciones_email n
    INNER JOIN public.citas c ON c.id = n.cita_id
    WHERE n.id = p_id;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'REGISTRO_NO_ENCONTRADO'; END IF;
    PERFORM petstore_private.requerir_acceso_sucursal(v_sucursal_id);

    UPDATE public.notificaciones_email
    SET procesando_token = gen_random_uuid(),
        procesando_en = CURRENT_TIMESTAMP,
        intentos = intentos + 1,
        actualizado_en = CURRENT_TIMESTAMP
    WHERE id = p_id
      AND estado = 'pending'
      AND destinatario IS NOT NULL
      AND (procesando_token IS NULL OR procesando_en < CURRENT_TIMESTAMP - INTERVAL '10 minutes')
    RETURNING procesando_token INTO v_token;
    IF NOT FOUND THEN RETURN NULL; END IF;

    RETURN (
        SELECT TO_JSONB(n) || JSONB_BUILD_OBJECT(
            'cliente_nombre', cl.nombre,
            'mascota_nombre', m.nombre,
            'sucursal_nombre', s.nombre,
            'servicio_nombre', sv.nombre
        )
        FROM public.notificaciones_email n
        INNER JOIN public.citas c ON c.id = n.cita_id
        INNER JOIN public.mascotas m ON m.id = c.mascota_id
        INNER JOIN public.clientes cl ON cl.id = m.cliente_id
        INNER JOIN public.sucursales s ON s.id = c.sucursal_id
        INNER JOIN public.registros_servicio rs ON rs.id = n.registro_servicio_id
        INNER JOIN public.servicios sv ON sv.id = rs.servicio_id
        WHERE n.id = p_id
    ) || JSONB_BUILD_OBJECT('procesando_token', v_token);
END;
$$;

CREATE FUNCTION public.notificaciones_email_reintentar(
    p_id BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
    v_sucursal_id BIGINT;
    v_token UUID;
BEGIN
    PERFORM petstore_private.requerir_usuario_activo();
    SELECT c.sucursal_id INTO v_sucursal_id
    FROM public.notificaciones_email n
    INNER JOIN public.citas c ON c.id = n.cita_id
    WHERE n.id = p_id;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'REGISTRO_NO_ENCONTRADO'; END IF;
    PERFORM petstore_private.requerir_acceso_sucursal(v_sucursal_id);

    UPDATE public.notificaciones_email
    SET estado = 'pending',
        ultimo_error = NULL,
        procesando_token = gen_random_uuid(),
        procesando_en = CURRENT_TIMESTAMP,
        intentos = intentos + 1,
        actualizado_en = CURRENT_TIMESTAMP
    WHERE id = p_id
      AND estado = 'failed'
      AND destinatario IS NOT NULL
      AND ultimo_error IS DISTINCT FROM 'recipient_email_missing'
      AND (procesando_token IS NULL OR procesando_en < CURRENT_TIMESTAMP - INTERVAL '10 minutes')
    RETURNING procesando_token INTO v_token;
    IF NOT FOUND THEN RETURN NULL; END IF;

    RETURN (
        SELECT TO_JSONB(n) || JSONB_BUILD_OBJECT(
            'cliente_nombre', cl.nombre,
            'mascota_nombre', m.nombre,
            'sucursal_nombre', s.nombre,
            'servicio_nombre', sv.nombre,
            'procesando_token', v_token
        )
        FROM public.notificaciones_email n
        INNER JOIN public.citas c ON c.id = n.cita_id
        INNER JOIN public.mascotas m ON m.id = c.mascota_id
        INNER JOIN public.clientes cl ON cl.id = m.cliente_id
        INNER JOIN public.sucursales s ON s.id = c.sucursal_id
        INNER JOIN public.registros_servicio rs ON rs.id = n.registro_servicio_id
        INNER JOIN public.servicios sv ON sv.id = rs.servicio_id
        WHERE n.id = p_id
    );
END;
$$;

CREATE FUNCTION public.notificaciones_email_marcar_enviada(
    p_id BIGINT,
    p_token UUID,
    p_proveedor_mensaje_id TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
    PERFORM petstore_private.requerir_usuario_activo();
    UPDATE public.notificaciones_email
    SET estado = 'sent',
        proveedor_mensaje_id = NULLIF(BTRIM(p_proveedor_mensaje_id), ''),
        ultimo_error = NULL,
        enviado_en = CURRENT_TIMESTAMP,
        procesando_token = NULL,
        procesando_en = NULL,
        actualizado_en = CURRENT_TIMESTAMP
    WHERE id = p_id AND estado = 'pending' AND procesando_token = p_token;
    RETURN FOUND;
END;
$$;

CREATE FUNCTION public.notificaciones_email_marcar_fallida(
    p_id BIGINT,
    p_token UUID,
    p_error TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
    PERFORM petstore_private.requerir_usuario_activo();
    UPDATE public.notificaciones_email
    SET estado = 'failed',
        ultimo_error = LEFT(COALESCE(NULLIF(BTRIM(p_error), ''), 'email_send_failed'), 100),
        procesando_token = NULL,
        procesando_en = NULL,
        actualizado_en = CURRENT_TIMESTAMP
    WHERE id = p_id AND estado = 'pending' AND procesando_token = p_token;
    RETURN FOUND;
END;
$$;

CREATE FUNCTION public.notificaciones_email_listar(
    p_limite BIGINT DEFAULT 25,
    p_offset BIGINT DEFAULT 0,
    p_desde DATE DEFAULT NULL,
    p_hasta DATE DEFAULT NULL,
    p_cliente_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
DECLARE v_resultado JSONB;
BEGIN
    PERFORM petstore_private.requerir_usuario_activo();
    PERFORM petstore_private.validar_paginacion(p_limite, p_offset);
    IF p_desde IS NOT NULL AND p_hasta IS NOT NULL AND p_hasta < p_desde THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'RANGO_DE_FECHAS_INVALIDO';
    END IF;

    WITH base AS (
        SELECT n.*, cl.nombre AS cliente_nombre, m.nombre AS mascota_nombre,
               s.nombre AS sucursal_nombre, sv.nombre AS servicio_nombre
        FROM public.notificaciones_email n
        INNER JOIN public.citas c ON c.id = n.cita_id
        INNER JOIN public.mascotas m ON m.id = c.mascota_id
        INNER JOIN public.clientes cl ON cl.id = m.cliente_id
        INNER JOIN public.sucursales s ON s.id = c.sucursal_id
        INNER JOIN public.registros_servicio rs ON rs.id = n.registro_servicio_id
        INNER JOIN public.servicios sv ON sv.id = rs.servicio_id
        WHERE (p_desde IS NULL OR n.creado_en >= (p_desde::TIMESTAMP AT TIME ZONE 'America/Guatemala'))
          AND (p_hasta IS NULL OR n.creado_en < ((p_hasta + 1)::TIMESTAMP AT TIME ZONE 'America/Guatemala'))
          AND (p_cliente_id IS NULL OR n.cliente_id = p_cliente_id)
          AND petstore_private.tiene_acceso_sucursal(c.sucursal_id)
    ), pagina AS (
        SELECT * FROM base ORDER BY creado_en DESC, id DESC LIMIT p_limite OFFSET p_offset
    )
    SELECT JSONB_BUILD_OBJECT(
        'datos', COALESCE((SELECT JSONB_AGG(TO_JSONB(p) ORDER BY p.creado_en DESC, p.id DESC) FROM pagina p), '[]'::JSONB),
        'total', (SELECT COUNT(*) FROM base),
        'limite', p_limite,
        'offset', p_offset
    ) INTO v_resultado;
    RETURN v_resultado;
END;
$$;

REVOKE ALL ON FUNCTION public.notificaciones_email_servicio_completado_preparar(BIGINT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.notificaciones_email_reclamar_pendiente(BIGINT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.notificaciones_email_reintentar(BIGINT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.notificaciones_email_marcar_enviada(BIGINT, UUID, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.notificaciones_email_marcar_fallida(BIGINT, UUID, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.notificaciones_email_listar(BIGINT, BIGINT, DATE, DATE, BIGINT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.notificaciones_email_servicio_completado_preparar(BIGINT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.notificaciones_email_reclamar_pendiente(BIGINT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.notificaciones_email_reintentar(BIGINT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.notificaciones_email_marcar_enviada(BIGINT, UUID, TEXT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.notificaciones_email_marcar_fallida(BIGINT, UUID, TEXT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.notificaciones_email_listar(BIGINT, BIGINT, DATE, DATE, BIGINT) TO authenticated, service_role;

COMMIT;
