CREATE TABLE public.fidelidad_clientes (
    cliente_id BIGINT PRIMARY KEY
        REFERENCES public.clientes(id) ON DELETE RESTRICT,
    creditos_acumulados BIGINT NOT NULL DEFAULT 0
        CHECK (creditos_acumulados >= 0),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.fidelidad_ajustes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL
        REFERENCES public.clientes(id) ON DELETE RESTRICT,
    creditos_anteriores BIGINT NOT NULL CHECK (creditos_anteriores >= 0),
    creditos_nuevos BIGINT NOT NULL CHECK (creditos_nuevos >= 0),
    completados_anteriores INTEGER NOT NULL CHECK (completados_anteriores >= 0),
    completados_nuevos INTEGER NOT NULL CHECK (completados_nuevos >= 0),
    motivo TEXT NOT NULL CHECK (BTRIM(motivo) <> ''),
    usuario_id UUID NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_fidelidad_ajustes_cliente_creado
    ON public.fidelidad_ajustes (cliente_id, creado_en DESC);

ALTER TABLE public.fidelidad_clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fidelidad_ajustes ENABLE ROW LEVEL SECURITY;

CREATE POLICY fidelidad_clientes_select
ON public.fidelidad_clientes FOR SELECT TO authenticated
USING ((SELECT petstore_private.usuario_activo()));

CREATE POLICY fidelidad_clientes_update
ON public.fidelidad_clientes FOR UPDATE TO authenticated
USING ((SELECT petstore_private.es_admin_propietario()))
WITH CHECK ((SELECT petstore_private.es_admin_propietario()));

CREATE POLICY fidelidad_ajustes_select
ON public.fidelidad_ajustes FOR SELECT TO authenticated
USING ((SELECT petstore_private.es_admin_propietario()));

CREATE POLICY fidelidad_ajustes_insert
ON public.fidelidad_ajustes FOR INSERT TO authenticated
WITH CHECK ((SELECT petstore_private.es_admin_propietario()));

GRANT SELECT, UPDATE ON TABLE public.fidelidad_clientes TO authenticated;
GRANT SELECT, INSERT ON TABLE public.fidelidad_ajustes TO authenticated;
GRANT ALL PRIVILEGES ON TABLE public.fidelidad_clientes, public.fidelidad_ajustes TO service_role;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.fidelidad_ajustes_id_seq TO authenticated, service_role;

CREATE TRIGGER trg_fidelidad_clientes_actualizado_en
BEFORE UPDATE ON public.fidelidad_clientes
FOR EACH ROW EXECUTE FUNCTION public.establecer_actualizado_en();

INSERT INTO public.fidelidad_clientes (cliente_id, creditos_acumulados)
SELECT c.id,
       COALESCE((
           SELECT COUNT(*)
           FROM public.registros_servicio rs
           INNER JOIN public.citas ci ON ci.id = rs.cita_id
           INNER JOIN public.mascotas m ON m.id = ci.mascota_id
           LEFT JOIN public.cupones cp ON cp.id = rs.cupon_id
           CROSS JOIN public.configuracion_sistema config
           WHERE m.cliente_id = c.id
             AND rs.estado = 'completado'
             AND rs.activo = TRUE
             AND rs.fin_real >= config.fidelidad_inicia_en
             AND (rs.cupon_id IS NULL OR cp.uso_unico = FALSE)
             AND config.id = 1
       ), 0)
FROM public.clientes c
ON CONFLICT (cliente_id) DO NOTHING;

CREATE OR REPLACE FUNCTION petstore_private.registro_servicio_cuenta_fidelidad(
    p_estado public.estado_registro_servicio,
    p_activo BOOLEAN,
    p_fin_real TIMESTAMPTZ,
    p_cupon_id UUID
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.configuracion_sistema config
        WHERE config.id = 1
          AND p_estado = 'completado'
          AND p_activo = TRUE
          AND p_fin_real >= config.fidelidad_inicia_en
          AND (
              p_cupon_id IS NULL
              OR NOT EXISTS (
                  SELECT 1
                  FROM public.cupones cp
                  WHERE cp.id = p_cupon_id
                    AND cp.uso_unico = TRUE
              )
          )
    );
$$;

CREATE OR REPLACE FUNCTION petstore_private.actualizar_fidelidad_desde_registro()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_cliente_id BIGINT;
    v_delta INTEGER := 0;
    v_anterior_cuenta BOOLEAN := FALSE;
    v_nueva_cuenta BOOLEAN;
BEGIN
    SELECT m.cliente_id
    INTO v_cliente_id
    FROM public.citas ci
    INNER JOIN public.mascotas m ON m.id = ci.mascota_id
    WHERE ci.id = NEW.cita_id;

    v_nueva_cuenta := petstore_private.registro_servicio_cuenta_fidelidad(
        NEW.estado, NEW.activo, NEW.fin_real, NEW.cupon_id
    );
    IF TG_OP = 'UPDATE' THEN
        v_anterior_cuenta := petstore_private.registro_servicio_cuenta_fidelidad(
            OLD.estado, OLD.activo, OLD.fin_real, OLD.cupon_id
        );
    END IF;

    IF v_nueva_cuenta AND NOT v_anterior_cuenta THEN
        v_delta := 1;
    ELSIF v_anterior_cuenta AND NOT v_nueva_cuenta THEN
        v_delta := -1;
    END IF;

    IF v_delta = 0 OR v_cliente_id IS NULL THEN
        RETURN NEW;
    END IF;

    PERFORM 1 FROM public.clientes WHERE id = v_cliente_id FOR UPDATE;

    IF v_delta > 0 THEN
        INSERT INTO public.fidelidad_clientes (cliente_id, creditos_acumulados)
        VALUES (v_cliente_id, 1)
        ON CONFLICT (cliente_id) DO UPDATE
        SET creditos_acumulados = public.fidelidad_clientes.creditos_acumulados + 1;
    ELSE
        UPDATE public.fidelidad_clientes
        SET creditos_acumulados = GREATEST(0, creditos_acumulados - 1)
        WHERE cliente_id = v_cliente_id;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_actualizar_fidelidad_desde_registro ON public.registros_servicio;
CREATE TRIGGER trg_actualizar_fidelidad_desde_registro
AFTER INSERT OR UPDATE OF estado, activo, fin_real, cupon_id ON public.registros_servicio
FOR EACH ROW EXECUTE FUNCTION petstore_private.actualizar_fidelidad_desde_registro();

CREATE OR REPLACE FUNCTION petstore_private.crear_fidelidad_cliente()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.fidelidad_clientes (cliente_id)
    VALUES (NEW.id)
    ON CONFLICT (cliente_id) DO NOTHING;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_crear_fidelidad_cliente ON public.clientes;
CREATE TRIGGER trg_crear_fidelidad_cliente
AFTER INSERT ON public.clientes
FOR EACH ROW EXECUTE FUNCTION petstore_private.crear_fidelidad_cliente();

CREATE OR REPLACE FUNCTION public.clientes_progreso_fidelidad_listar()
RETURNS JSONB
LANGUAGE plpgsql SECURITY INVOKER SET search_path = ''
AS $$
DECLARE v_resultado JSONB;
BEGIN
    PERFORM petstore_private.requerir_usuario_activo();

    SELECT COALESCE(JSONB_AGG(JSONB_BUILD_OBJECT(
        'cliente_id', c.id,
        'completados', MOD(COALESCE(fc.creditos_acumulados, 0), config.servicios_requeridos_cupon),
        'requeridos', config.servicios_requeridos_cupon
    ) ORDER BY c.id), '[]'::JSONB)
    INTO v_resultado
    FROM public.clientes c
    CROSS JOIN public.configuracion_sistema config
    LEFT JOIN public.fidelidad_clientes fc ON fc.cliente_id = c.id
    WHERE c.activo = TRUE
      AND config.id = 1;

    RETURN v_resultado;
END;
$$;

CREATE FUNCTION public.clientes_fidelidad_actualizar(
    p_cliente_id BIGINT,
    p_completados INTEGER,
    p_motivo TEXT
)
RETURNS public.fidelidad_clientes
LANGUAGE plpgsql SECURITY INVOKER SET search_path = ''
AS $$
DECLARE
    v_actor UUID;
    v_requeridos INTEGER;
    v_anterior BIGINT;
    v_nuevo BIGINT;
    v_fila public.fidelidad_clientes;
BEGIN
    v_actor := petstore_private.requerir_admin_propietario();
    PERFORM petstore_private.establecer_actor();

    IF p_motivo IS NULL OR BTRIM(p_motivo) = '' THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'MOTIVO_REQUERIDO';
    END IF;

    SELECT servicios_requeridos_cupon
    INTO v_requeridos
    FROM public.configuracion_sistema
    WHERE id = 1;
    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'CONFIGURACION_SISTEMA_NO_ENCONTRADA';
    END IF;
    IF p_completados IS NULL OR p_completados < 0 OR p_completados >= v_requeridos THEN
        RAISE EXCEPTION USING ERRCODE = 'PV001', MESSAGE = 'PROGRESO_FIDELIDAD_INVALIDO';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.clientes WHERE id = p_cliente_id AND activo = TRUE) THEN
        RAISE EXCEPTION USING ERRCODE = 'PN001', MESSAGE = 'CLIENTE_NO_ENCONTRADO';
    END IF;

    SELECT COALESCE(creditos_acumulados, 0)
    INTO v_anterior
    FROM public.fidelidad_clientes
    WHERE cliente_id = p_cliente_id
    FOR UPDATE;

    v_anterior := COALESCE(v_anterior, 0);
    v_nuevo := v_anterior - MOD(v_anterior, v_requeridos) + p_completados;

    INSERT INTO public.fidelidad_clientes (cliente_id, creditos_acumulados)
    VALUES (p_cliente_id, v_nuevo)
    ON CONFLICT (cliente_id) DO UPDATE
    SET creditos_acumulados = EXCLUDED.creditos_acumulados
    RETURNING * INTO v_fila;

    INSERT INTO public.fidelidad_ajustes (
        cliente_id,
        creditos_anteriores,
        creditos_nuevos,
        completados_anteriores,
        completados_nuevos,
        motivo,
        usuario_id
    )
    VALUES (
        p_cliente_id,
        v_anterior,
        v_nuevo,
        MOD(v_anterior, v_requeridos),
        p_completados,
        BTRIM(p_motivo),
        v_actor
    );

    PERFORM petstore_private.auditar_cambio(
        'fidelidad_clientes', p_cliente_id::TEXT, 'ajustar',
        JSONB_BUILD_OBJECT('completados', MOD(v_anterior, v_requeridos)),
        JSONB_BUILD_OBJECT('completados', p_completados),
        NULL, BTRIM(p_motivo)
    );

    RETURN v_fila;
END;
$$;

CREATE FUNCTION public.clientes_fidelidad_reconciliar()
RETURNS JSONB
LANGUAGE plpgsql SECURITY INVOKER SET search_path = ''
AS $$
DECLARE v_resultado JSONB;
BEGIN
    PERFORM petstore_private.requerir_admin_propietario();

    WITH config AS (
        SELECT servicios_requeridos_cupon, fidelidad_inicia_en
        FROM public.configuracion_sistema
        WHERE id = 1
    ), esperados AS (
        SELECT c.id AS cliente_id,
               c.nombre AS cliente_nombre,
               COUNT(rs.id)::BIGINT AS servicios_completados
        FROM public.clientes c
        CROSS JOIN config
        LEFT JOIN public.mascotas m ON m.cliente_id = c.id
        LEFT JOIN public.citas ci ON ci.mascota_id = m.id
        LEFT JOIN public.registros_servicio rs
           ON rs.cita_id = ci.id
           AND rs.estado = 'completado'
           AND rs.activo = TRUE
           AND rs.fin_real >= config.fidelidad_inicia_en
        LEFT JOIN public.cupones cp ON cp.id = rs.cupon_id
        WHERE c.activo = TRUE
          AND (rs.cupon_id IS NULL OR cp.uso_unico = FALSE)
        GROUP BY c.id, c.nombre, config.servicios_requeridos_cupon
    ), diferencias AS (
        SELECT e.cliente_id,
               e.cliente_nombre,
               MOD(COALESCE(fc.creditos_acumulados, 0), config.servicios_requeridos_cupon) AS actual,
               MOD(e.servicios_completados, config.servicios_requeridos_cupon) AS esperado,
               e.servicios_completados
        FROM esperados e
        CROSS JOIN config
        LEFT JOIN public.fidelidad_clientes fc ON fc.cliente_id = e.cliente_id
    )
    SELECT COALESCE(JSONB_AGG(JSONB_BUILD_OBJECT(
        'cliente_id', cliente_id,
        'cliente_nombre', cliente_nombre,
        'actual', actual,
        'esperado', esperado,
        'servicios_completados', servicios_completados,
        'requeridos', config.servicios_requeridos_cupon
    ) ORDER BY cliente_nombre, cliente_id) FILTER (WHERE actual IS DISTINCT FROM esperado), '[]'::JSONB)
    INTO v_resultado
    FROM diferencias
    CROSS JOIN config;

    RETURN v_resultado;
END;
$$;

REVOKE ALL ON FUNCTION public.clientes_fidelidad_actualizar(BIGINT, INTEGER, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.clientes_fidelidad_reconciliar() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.clientes_fidelidad_actualizar(BIGINT, INTEGER, TEXT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.clientes_fidelidad_reconciliar() TO authenticated, service_role;
